# Default api
GET http://localhost:7071/api

# Create a new 'Pharmacy'
POST http://localhost:7071/api/pharmacies HTTP/1.1
content-type: application/json

{
  "pharmacy_name": "Wallgreens",
  "city": "San Diego",
  "state": "California",
  "zip_code": 94003
}

# List all the Pharmacies
GET http://localhost:7071/api/pharmacies

# List Pharmacy by Id
GET http://localhost:7071/api/pharmacies/136cf9f9-f755-4f7e-b84b-4a9e8239943d

# Update Pharmacy by Id
PUT http://localhost:7071/api/pharmacies/7e459309-538a-4918-99e8-806da7b693e5 HTTP/1.1
content-type: application/json

{
  "pharmacy_name": "Pharma Hall",
  "city": "New York",
  "state": "New York City",
  "zip_code": 22795-999
}

# Delete Pharmacy by Id
DELETE http://localhost:7071/api/pharmacies/c34f4916-124a-440c-890f-813ff7fd2004 HTTP/1.1